theme:          jekyll-theme-tactile
title:          Giuseppe Di Natale
author:         dinatale2
locale:         en_US
url:            https://dinatale2.github.io
google:
  analytics:    UA-145923388-1
